version: '3'

services:
  keycloak:
    image: jboss/keycloak:15.0.2
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    volumes:
      - ./realm.json:/tmp/realm.json
      - ./login.ftl:/opt/jboss/keycloak/themes/base/login/login.ftl
      - ./target/recaptcha-login.jar:/opt/jboss/keycloak/standalone/deployments/recaptcha-login.jar
      - ./startup-scripts/:/opt/jboss/startup-scripts/
    ports:
      - 8080:8080